disabled_rules: # rule identifiers turned on by default to exclude from running
  - type_name
  - identifier_name
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity
  - nesting
  - type_body_length
  - todo
  - opening_brace

opt_in_rules:
  - force_unwrapping

force_unwrapping:
  severity: error

line_length: 500
